http://adventofcode.com/2017/day/2

* Part one
  #+BEGIN_QUOTE
    For each row, determine the difference between the largest value and the smallest value;
    the checksum is the sum of all of these differences.
  #+END_QUOTE

** IRC Responses
 I was confused about ~split_whitespace~, the responses below are what I got by asking in #rust-beginners.
#+BEGIN_QUOTE
 <cjm> asimpson: if you ever have a map operation that generates sub-iterators
       and you want to collect all the results, flat_map is the tool for the
       job
       https://play.rust-lang.org/?gist=6635e844624410c10d1f1ac0258d3f23&version=stable
                                                                         [10:33]
 <cjm> asimpson: but newlines do also count as whitespace, so you can just do
       this
       https://play.rust-lang.org/?gist=96aac505b4e50a3ced6925a81bf237cb&version=stable
 <lucasem> asimpson, cjm: you can also use str::split_whitespace directly
           https://play.rust-lang.org/?gist=99437fb0b82491ff23a161ae4dae51a4&version=stable
 <qoxncyha> you dont need the ::<_>:
            https://play.rust-lang.org/?gist=9d5f7d1ac03fe57bea882295dd8bb9c8&version=stable
                                                                         [10:38]
 <asimpson> qoxncyha: oh right!                                          [10:39]
 <lucasem> (you also don't need the &str)
           https://play.rust-lang.org/?gist=f525ebce22590b594d7182292b6e8cb5&version=stable
                                                                         [10:42]
 <asimpson> lucasem: that brings up another question I've had before. Is it
            considered best practice to declare the type if you know it or use
            the _ whenever possible?                                     [10:44]
 <lucasem> asimpson: it depends on how obvious it is
 <lucasem> in this case, it's obviously a vec of &str, so it's fine to leave it
           out                                                           [10:45]
 <qoxncyha> i like to specify types even when theyre not needed sometimes
 <asimpson> at that point it's a "developer ergonomic" thing rather than what's
            best for the compiler.
 <lucasem> asimpson: yeah
 <lucasem> use code style / software design judgement                    [10:46]
#+END_QUOTE

* Part two
  #+BEGIN_QUOTE
  "Based on what we're seeing, it looks like all the User wanted is some information about the evenly divisible values in the spreadsheet. Unfortunately, none of us are equipped for that kind of calculation - most of us specialize in bitwise operations."

It sounds like the goal is to find the only two numbers in each row where one evenly divides the other - that is, where the result of the division operation is a whole number. They would like you to find those numbers on each line, divide them, and add up each line's result.
  #+END_QUOTE

  #+BEGIN_QUOTE
  In the first row, the only two numbers that evenly divide are 8 and 2; the result of this division is 4.
In the second row, the two numbers are 9 and 3; the result is 3.
In the third row, the result is 2.
In this example, the sum of the results would be 4 + 3 + 2 = 9.
  #+END_QUOTE
